name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file ./backend/Dockerfile --tag anastazijakovach/backend_vinozito:$(date +%s)

    - name: Push the Docker image to DockerHub
      run: docker push anastazijakovach/backend_vinozito:$(date +%s)
